version: '3'

services:
    python3:
        container_name: python3
        build: 
            context: .
            dockerfile: docker/python/Dockerfile
        restart: always
        working_dir: '/root/src'
        tty: true
        volumes:
            - ${PWD}/src:/root/src
        networks:
            - dynamodb-local-network

    dynamodb-local:
        container_name: dev-dynamodb-local
        image: amazon/dynamodb-local:latest
        user: root
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
        volumes:
            - ${PWD}/dynamodb-local-data:/data
        ports:
            - 8000:8000
        networks:
            - dynamodb-local-network

    dynamodb-admin:
        container_name: dev-dynamodb-admin
        image: aaronshaf/dynamodb-admin:latest
        environment:
            - DYNAMO_ENDPOINT=dynamodb-local:8000
        ports:
            - 8001:8001
        depends_on:
            - dynamodb-local
        networks:
            - dynamodb-local-network

volumes:
    dynamodb-local-data:

networks:
    dynamodb-local-network:
        driver: bridge
